"apiVersion": "batch/v1beta1"
"kind": "CronJob"
"metadata":
  "name": "pt-nightly-mnist-convergence-v3-8"
  "namespace": "automated"
"spec":
  "concurrencyPolicy": "Forbid"
  "jobTemplate":
    "spec":
      "activeDeadlineSeconds": 3600
      "backoffLimit": 2
      "template":
        "metadata":
          "annotations":
            "tf-version.cloud-tpus.google.com": "pytorch-nightly"
        "spec":
          "containers":
          - "args":
            - "python3"
            - "pytorch/xla/test/test_train_mp_mnist.py"
            - "--logdir=$(MODEL_DIR)"
            "env":
            - "name": "TEST_NAME"
              "value": "pt-nightly-mnist-convergence-v3-8"
            - "name": "POD_NAME"
              "valueFrom":
                "fieldRef":
                  "fieldPath": "metadata.name"
            - "name": "POD_UID"
              "valueFrom":
                "fieldRef":
                  "fieldPath": "metadata.uid"
            - "name": "POD_NAMESPACE"
              "valueFrom":
                "fieldRef":
                  "fieldPath": "metadata.namespace"
            - "name": "JOB_NAME"
              "valueFrom":
                "fieldRef":
                  "fieldPath": "metadata.labels['job-name']"
            - "name": "MODEL_DIR"
              "value": "gs://xl-ml-test-us-central1/k8s/mnist/convergence/v3-8/$(JOB_NAME)"
            - "name": "METRIC_COLLECTION_CONFIG"
              "value": "{\n \"bigquery_dataset_name\": \"xl_ml_metrics_dataset\",\n \"bigquery_table_name\": \"xl_ml_metrics_table\",\n \"default_aggregation_strategies\": [\n  \"final\"\n ],\n \"tags_to_ignore\": [\n  \"LearningRate\"\n ],\n \"write_to_bigquery\": \"True\"\n}"
            - "name": "REGRESSION_TEST_CONFIG"
              "value": "{\n \"base_comparison\": \"COMPARISON_GT\",\n \"base_threshold_expression\": \"v_mean + (v_stddev * 3.0)\",\n \"comparison_overrides\": {\n  \"Accuracy/test_final\": \"COMPARISON_LT\"\n },\n \"metric_opt_in_list\": [\n  \"Accuracy/test_final\",\n  \"ExecuteTime__Percentile_99_sec_final\",\n  \"CompileTime__Percentile_99_sec_final\"\n ],\n \"min_num_datapoints_before_alerting\": 1,\n \"threshold_expression_overrides\": {\n  \"Accuracy/test_final\": \"v_mean - (v_stddev * 3.0)\"\n },\n \"write_alerts_to_stackdriver\": \"True\",\n \"write_metrics_to_stackdriver\": \"True\"\n}"
            - "name": "XLA_USE_BF16"
              "value": "0"
            "image": "gcr.io/xl-ml-test/pytorch-xla:nightly"
            "name": "pt-nightly-mnist-convergence-v3-8"
            "resources":
              "limits":
                "cloud-tpus.google.com/preemptible-v3": 8
              "requests":
                "cpu": "4.5"
                "memory": "8Gi"
            "volumeMounts":
            - "mountPath": "/dev/shm"
              "name": "dshm"
          "restartPolicy": "Never"
          "volumes":
          - "emptyDir":
              "medium": "Memory"
            "name": "dshm"
          - "gcePersistentDisk":
              "fsType": "ext4"
              "pdName": "pytorch-datasets-pd-central1-b"
            "name": "datasets-pd"
  "schedule": "30 7 * * */2"