"apiVersion": "batch/v1beta1"
"kind": "CronJob"
"metadata":
  "name": "pt-nightly-resnet50-convergence-v3-8"
  "namespace": "automated"
"spec":
  "concurrencyPolicy": "Forbid"
  "jobTemplate":
    "spec":
      "activeDeadlineSeconds": 82800
      "backoffLimit": 2
      "template":
        "metadata":
          "annotations":
            "tf-version.cloud-tpus.google.com": "pytorch-nightly"
        "spec":
          "containers":
          - "args":
            - "python3"
            - "pytorch/xla/test/test_train_imagenet.py"
            - "--model=resnet50"
            - "--num_workers=64"
            - "--batch_size=128"
            - "--log_steps=200"
            - "--num_epochs=90"
            - "--datadir=/datasets/imagenet"
            - "--logdir=$(MODEL_DIR)"
            "env":
            - "name": "POD_NAME"
              "valueFrom":
                "fieldRef":
                  "fieldPath": "metadata.name"
            - "name": "POD_UID"
              "valueFrom":
                "fieldRef":
                  "fieldPath": "metadata.uid"
            - "name": "POD_NAMESPACE"
              "valueFrom":
                "fieldRef":
                  "fieldPath": "metadata.namespace"
            - "name": "JOB_NAME"
              "valueFrom":
                "fieldRef":
                  "fieldPath": "metadata.labels['job-name']"
            - "name": "METRIC_COLLECTION_CONFIG"
              "value": "{\n \"bigquery_dataset_name\": \"xl_ml_metrics_dataset\",\n \"bigquery_table_name\": \"xl_ml_metrics_table\",\n \"default_aggregation_strategies\": [\n  \"final\"\n ],\n \"tags_to_ignore\": [\n  \"LearningRate\"\n ],\n \"write_to_bigquery\": \"True\"\n}"
            - "name": "MODEL_DIR"
              "value": "gs://xl-ml-test-us-central1/k8s/resnet50/convergence/v3-8/$(JOB_NAME)"
            - "name": "REGRESSION_TEST_CONFIG"
              "value": "{\n \"bigquery_dataset_name\": \"xl_ml_metrics_dataset\",\n \"bigquery_table_name\": \"xl_ml_metrics_table\",\n \"metric_subset_to_alert\": [\n  \"ExecuteTime__Percentile_99_sec_final\",\n  \"CompileTime__Percentile_99_sec_final\",\n  \"job_status\",\n  \"total_wall_time\",\n  \"Accuracy/test_final\"\n ],\n \"metric_success_conditions\": {\n  \"Accuracy/test_final\": {\n   \"comparison\": \"greater\",\n   \"success_threshold\": {\n    \"fixed_value\": 76\n   }\n  },\n  \"CompileTime__Percentile_99_sec_final\": {\n   \"comparison\": \"less\",\n   \"success_threshold\": {\n    \"stddevs_from_mean\": 5\n   },\n   \"wait_for_n_points_of_history\": 10\n  },\n  \"ExecuteTime__Percentile_99_sec_final\": {\n   \"comparison\": \"less\",\n   \"success_threshold\": {\n    \"stddevs_from_mean\": 5\n   },\n   \"wait_for_n_points_of_history\": 10\n  },\n  \"job_status\": {\n   \"comparison\": \"equal\",\n   \"success_threshold\": {\n    \"fixed_value\": 0\n   }\n  },\n  \"total_wall_time\": {\n   \"comparison\": \"less\",\n   \"success_threshold\": {\n    \"stddevs_from_mean\": 5\n   },\n   \"wait_for_n_points_of_history\": 10\n  }\n },\n \"write_to_error_reporting\": \"True\"\n}"
            - "name": "TEST_NAME"
              "value": "pt-nightly-resnet50-convergence-v3-8"
            - "name": "XLA_USE_BF16"
              "value": "0"
            "image": "gcr.io/xl-ml-test/pytorch-xla:nightly"
            "imagePullPolicy": "Always"
            "name": "train"
            "resources":
              "limits":
                "cloud-tpus.google.com/preemptible-v3": 8
              "requests":
                "cpu": "90.0"
                "memory": "400Gi"
            "volumeMounts":
            - "mountPath": "/dev/shm"
              "name": "dshm"
            - "mountPath": "/datasets"
              "name": "datasets-pd"
              "readOnly": true
          "restartPolicy": "Never"
          "volumes":
          - "emptyDir":
              "medium": "Memory"
            "name": "dshm"
          - "gcePersistentDisk":
              "fsType": "ext4"
              "pdName": "pytorch-datasets-pd-central1-b"
              "readOnly": true
            "name": "datasets-pd"
  "schedule": "30 7 * * */2"