"apiVersion": "batch/v1beta1"
"kind": "CronJob"
"metadata":
  "name": "pt-nightly-mnist-convergence-v2-8"
"spec":
  "concurrencyPolicy": "Forbid"
  "jobTemplate":
    "spec":
      "activeDeadlineSeconds": 3600
      "backoffLimit": 2
      "template":
        "metadata":
          "annotations":
            "tf-version.cloud-tpus.google.com": "pytorch-nightly"
        "spec":
          "containers":
          - "args":
            - "python3"
            - "pytorch/xla/test/test_train_mp_mnist.py"
            "env":
            - "name": "TEST_NAME"
              "value": "pt-nightly-mnist-convergence-v2-8"
            - "name": "POD_NAME"
              "valueFrom":
                "fieldRef":
                  "fieldPath": "metadata.name"
            - "name": "POD_UID"
              "valueFrom":
                "fieldRef":
                  "fieldPath": "metadata.uid"
            - "name": "POD_NAMESPACE"
              "valueFrom":
                "fieldRef":
                  "fieldPath": "metadata.namespace"
            - "name": "JOB_NAME"
              "valueFrom":
                "fieldRef":
                  "fieldPath": "metadata.labels['job-name']"
            - "name": "MODEL_DIR"
              "value": "gs://xl-ml-test-us-central1/k8s/mnist/convergence/v2-8/$(JOB_NAME)"
            - "name": "METRIC_COLLECTION_CONFIG"
              "value": "null"
            - "name": "REGRESSION_TEST_CONFIG"
              "value": "null"
            - "name": "XLA_USE_BF16"
              "value": "0"
            "image": "gcr.io/xl-ml-test/pytorch-xla:nightly"
            "name": "pt-nightly-mnist-convergence-v2-8"
            "resources":
              "limits":
                "cloud-tpus.google.com/preemptible-v2": 8
              "requests":
                "cpu": "2.5"
                "memory": "8Gi"
            "volumeMounts":
            - "mountPath": "/dev/shm"
              "name": "dshm"
          "restartPolicy": "Never"
          "volumes":
          - "emptyDir":
              "medium": "Memory"
            "name": "dshm"
  "schedule": "30 7 * * */1"