"apiVersion": "batch/v1beta1"
"kind": "CronJob"
"metadata":
  "name": "tf-nightly-transformer-translate-functional-v2-8"
  "namespace": "automated"
"spec":
  "concurrencyPolicy": "Forbid"
  "jobTemplate":
    "spec":
      "activeDeadlineSeconds": 3600
      "backoffLimit": 2
      "template":
        "metadata":
          "annotations":
            "tf-version.cloud-tpus.google.com": "nightly-2.x"
        "spec":
          "containers":
          - "args":
            - "python3"
            - "official/transformer/v2/transformer_main.py"
            - "--tpu=$(KUBE_GOOGLE_CLOUD_TPU_ENDPOINTS)"
            - "--steps_between_evals=10000"
            - "--static_batch=true"
            - "--use_ctl=true"
            - "--param_set=big"
            - "--max_length=64"
            - "--decode_batch_size=32"
            - "--decode_max_length=97"
            - "--padded_decode=true"
            - "--distribution_strategy=tpu"
            - "--data_dir=gs://xl-ml-test-us-central1/data/transformer"
            - "--vocab_file=gs://xl-ml-test-us-central1/data/transformer/vocab.ende.32768"
            - "--bleu_source=gs://xl-ml-test-us-central1/data/transformer/newstest2014.en"
            - "--bleu_ref=gs://xl-ml-test-us-central1/data/transformer/newstest2014.de"
            - "--train_steps=20000"
            - "--batch_size=6144"
            - "--model_dir=$(MODEL_DIR)"
            "env":
            - "name": "TEST_NAME"
              "value": "tf-nightly-transformer-translate-functional-v2-8"
            - "name": "POD_NAME"
              "valueFrom":
                "fieldRef":
                  "fieldPath": "metadata.name"
            - "name": "POD_UID"
              "valueFrom":
                "fieldRef":
                  "fieldPath": "metadata.uid"
            - "name": "POD_NAMESPACE"
              "valueFrom":
                "fieldRef":
                  "fieldPath": "metadata.namespace"
            - "name": "JOB_NAME"
              "valueFrom":
                "fieldRef":
                  "fieldPath": "metadata.labels['job-name']"
            - "name": "MODEL_DIR"
              "value": "gs://xl-ml-test-us-central1/k8s/transformer-translate/functional/v2-8/$(JOB_NAME)"
            - "name": "METRIC_COLLECTION_CONFIG"
              "value": "{\n \"bigquery_dataset_name\": \"xl_ml_metrics_dataset\",\n \"bigquery_table_name\": \"xl_ml_metrics_table\",\n \"default_aggregation_strategies\": [\n  \"final\"\n ],\n \"write_to_bigquery\": \"True\"\n}"
            - "name": "REGRESSION_TEST_CONFIG"
              "value": "{\n \"base_comparison\": \"COMPARISON_GT\",\n \"base_threshold_expression\": \"v_mean + (v_stddev * 3.0)\",\n \"bigquery_dataset_name\": \"xl_ml_metrics_dataset\",\n \"bigquery_table_name\": \"xl_ml_metrics_table\",\n \"comparison_overrides\": {\n  \"epoch_sparse_categorical_accuracy_final\": \"COMPARISON_LT\"\n },\n \"min_num_datapoints_before_alerting\": 1,\n \"threshold_expression_overrides\": {\n  \"epoch_sparse_categorical_accuracy_final\": \"v_mean - (v_stddev * 3.0)\"\n },\n \"write_to_stackdriver\": \"True\"\n}"
            "image": "gcr.io/xl-ml-test/model-garden:nightly"
            "name": "tf-nightly-transformer-translate-functional-v2-8"
            "resources":
              "limits":
                "cloud-tpus.google.com/v2": 8
          "restartPolicy": "Never"
  "schedule": "0 */12 * * *"
