"apiVersion": "batch/v1beta1"
"kind": "CronJob"
"metadata":
  "name": "tf-nightly-mnist-convergence-v3-8"
"spec":
  "concurrencyPolicy": "Forbid"
  "jobTemplate":
    "spec":
      "activeDeadlineSeconds": 36000
      "backoffLimit": 2
      "template":
        "metadata":
          "annotations":
            "tf-version.cloud-tpus.google.com": "nightly-2.x"
        "spec":
          "containers":
          - "args":
            - "python3"
            - "official/vision/image_classification/mnist_main.py"
            - "--data_dir=gs://xl-ml-test-us-central1/data/mnist"
            - "--distribution_strategy=tpu"
            - "--clean"
            - "--batch_size=2048"
            - "--train_epochs=10"
            - "--epochs_between_evals=10"
            - "--model_dir=$(MODEL_DIR)"
            "env":
            - "name": "TEST_NAME"
              "value": "tf-nightly-mnist-convergence-v3-8"
            - "name": "POD_NAME"
              "valueFrom":
                "fieldRef":
                  "fieldPath": "metadata.name"
            - "name": "POD_UID"
              "valueFrom":
                "fieldRef":
                  "fieldPath": "metadata.uid"
            - "name": "POD_NAMESPACE"
              "valueFrom":
                "fieldRef":
                  "fieldPath": "metadata.namespace"
            - "name": "JOB_NAME"
              "valueFrom":
                "fieldRef":
                  "fieldPath": "metadata.labels['job-name']"
            - "name": "MODEL_DIR"
              "value": "gs://xl-ml-test-us-central1/k8s/mnist/convergence/v3-8/$(JOB_NAME)"
            - "name": "METRIC_COLLECTION_CONFIG"
              "value": "{\n \"bigquery_dataset_name\": \"xl_ml_metrics_dataset\",\n \"bigquery_table_name\": \"xl_ml_metrics_table\",\n \"default_aggregation_strategies\": [\n  \"final\"\n ],\n \"write_to_bigquery\": \"True\"\n}"
            - "name": "REGRESSION_TEST_CONFIG"
              "value": "{\n \"base_comparison\": \"COMPARISON_GT\",\n \"base_threshold_expression\": \"v_mean + (v_stddev * 3.0)\",\n \"comparison_overrides\": {\n  \"epoch_sparse_categorical_accuracy_final\": \"COMPARISON_LT\"\n },\n \"min_num_datapoints_before_alerting\": 1,\n \"threshold_expression_overrides\": {\n  \"epoch_sparse_categorical_accuracy_final\": \"v_mean - (v_stddev * 3.0)\"\n },\n \"write_alerts_to_stackdriver\": \"True\",\n \"write_metrics_to_stackdriver\": \"True\"\n}"
            "image": "gcr.io/xl-ml-test/model-garden:nightly"
            "name": "tf-nightly-mnist-convergence-v3-8"
            "resources":
              "limits":
                "cloud-tpus.google.com/v3": 8
          "restartPolicy": "Never"
  "schedule": "30 7 * * */1"