"apiVersion": "batch/v1beta1"
"kind": "CronJob"
"metadata":
  "name": "tf-nightly-resnet-ctl-functional-v3-8"
  "namespace": "automated"
"spec":
  "concurrencyPolicy": "Forbid"
  "jobTemplate":
    "spec":
      "activeDeadlineSeconds": 3600
      "backoffLimit": 2
      "template":
        "metadata":
          "annotations":
            "tf-version.cloud-tpus.google.com": "nightly-2.x"
        "spec":
          "containers":
          - "args":
            - "python3"
            - "official/vision/image_classification/resnet_ctl_imagenet_main.py"
            - "--tpu=$(KUBE_GOOGLE_CLOUD_TPU_ENDPOINTS)"
            - "--data_dir=gs://imagenet-us-central1/train"
            - "--distribution_strategy=tpu"
            - "--batch_size=1024"
            - "--steps_per_loop=500"
            - "--use_synthetic_data=false"
            - "--dtype=fp32"
            - "--enable_eager=true"
            - "--enable_tensorboard=true"
            - "--log_steps=50"
            - "--single_l2_loss_op=true"
            - "--use_tf_function=true"
            - "--batch_size=2048"
            - "--train_epochs=1"
            - "--epochs_between_evals=1"
            - "--model_dir=$(MODEL_DIR)"
            "env":
            - "name": "METRIC_COLLECTION_CONFIG"
              "value": "{\n \"bigquery_dataset_name\": \"xl_ml_metrics_dataset\",\n \"bigquery_table_name\": \"xl_ml_metrics_table\",\n \"default_aggregation_strategies\": [\n  \"final\"\n ],\n \"write_to_bigquery\": \"True\"\n}"
            - "name": "MODEL_DIR"
              "value": "gs://xl-ml-test-us-central1/k8s/resnet-ctl/functional/v3-8/$(JOB_NAME)"
            - "name": "REGRESSION_TEST_CONFIG"
              "value": "{\n \"bigquery_dataset_name\": \"xl_ml_metrics_dataset\",\n \"bigquery_table_name\": \"xl_ml_metrics_table\",\n \"metric_success_conditions\": {\n  \"job_status\": {\n   \"comparison\": \"equal\",\n   \"success_threshold\": {\n    \"fixed_value\": 0\n   }\n  },\n  \"total_wall_time\": {\n   \"comparison\": \"less\",\n   \"success_threshold\": {\n    \"stddevs_from_mean\": 5\n   },\n   \"wait_for_n_points_of_history\": 10\n  }\n },\n \"write_to_error_reporting\": \"True\"\n}"
            - "name": "TEST_NAME"
              "value": "tf-nightly-resnet-ctl-functional-v3-8"
            - "name": "POD_NAME"
              "valueFrom":
                "fieldRef":
                  "fieldPath": "metadata.name"
            - "name": "POD_UID"
              "valueFrom":
                "fieldRef":
                  "fieldPath": "metadata.uid"
            - "name": "POD_NAMESPACE"
              "valueFrom":
                "fieldRef":
                  "fieldPath": "metadata.namespace"
            - "name": "JOB_NAME"
              "valueFrom":
                "fieldRef":
                  "fieldPath": "metadata.labels['job-name']"
            "image": "gcr.io/xl-ml-test/model-garden:nightly"
            "imagePullPolicy": "Always"
            "name": "train"
            "resources":
              "limits":
                "cloud-tpus.google.com/preemptible-v3": 8
          "restartPolicy": "Never"
  "schedule": "0 */12 * * *"